import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClashDisplay } from "@/fonts";
import { ScrollProvider } from "@/providers/ScrollProvider";

export const metadata: Metadata = {
  title: "Dia Diamonds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ClashDisplay.variable} antialiased`}>
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
