import type { Metadata } from "next";
import "./globals.css";
import { ClashDisplay, BaskerVilleSC, ClashGrotesk } from "@/fonts";
import { Providers } from "./providers";
import Navbar from "@/components/Reusable/Navbar";
import Footer from "@/components/Reusable/Footer";


export const metadata: Metadata = {
  title: "Dia Diamonds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ClashDisplay.variable} ${BaskerVilleSC.variable} ${ClashGrotesk.variable} antialiased`}>
        <Navbar />  
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
